apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sumeetnirmale00/argocd.git
    targetRevision: main
    path: argocd-demos/multicluster/online-shop # Path within the repo
  destination:
    server: https://172.18.0.5:6443  # Production cluster API server URL here, run `argocd cluster list` to get the URL
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    