apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sumeetnirmale00/argocd.git
    targetRevision: main
    path: argocd-demos/cli_approach/apache      # Path to apache manifests
  destination:
    server: https://172.18.0.4:6443  # from `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true